### ISSUE TITLE
bug when delete sleeping

### ISSUE THREAD

**Issue by sbounmy** [sbounmy/hackerhouse_bubble#1]
<img width="845" alt="CleanShot 2022-09-02 at 16 49 25@2x" src="https://user-images.githubusercontent.com/159814/188176142-5b95639b-c45a-4be3-bf95-5d3b4cbf11b1.png">

**Comment by Mihajahackerhouse** [comment]
@sbounmy 

Ce n'est pas un bug... Le plan est just archivé comme on l'avait décidé au début
J'ai juste aligné les blocs et enlevé l'icon supprimé de l'input ajouter un nom de lit

**Comment by Mihajahackerhouse** [comment]
![Image](https://user-images.githubusercontent.com/112725844/188596066-ef243785-d76a-4f8c-9504-177b95dc0e69.png)

**Comment by Mihajahackerhouse** [comment]
![Image](https://user-images.githubusercontent.com/112725844/188815718-aed12739-975e-4c3a-b446-286dacafaa24.png)

**Comment by Mihajahackerhouse** [comment]
Ajout de la condition archived différent de yes pour ne pas affiché les plans archivés
